replicaCount: 1

image:
  repository: ghcr.io/heremias/redwoodjs-app-web-main
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "97cb1dd6888e994a9a5076f94b4c41584daf793b"

imagePullSecrets:
  - name: redwoods

service:
  type: LoadBalancer
  port: 80
  targetPort: 8910

configMap:
  name: reactconfig

ingress:
  enabled: false
