replicaCount: 1

image:
  repository: ghcr.io/heremias/redwoodjs-app-web-main
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "87e663232befca16b40b48fe69d4969c103138b9"

imagePullSecrets:
  - name: redwoods

service:
  type: LoadBalancer
  port: 80
  targetPort: 8910

configMap:
  name: reactconfig

ingress:
  enabled: false
