replicaCount: 1

image:
  repository: ghcr.io/heremias/redwoodjs-app-web-main
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "b0b6871c40b79e1255a97adb3ba9b1cf5a19e2b3"

imagePullSecrets:
  - name: redwoods

service:
  type: LoadBalancer
  port: 80
  targetPort: 8910

configMap:
  name: reactconfig

ingress:
  enabled: false
