replicaCount: 1

image:
  repository: ghcr.io/heremias/redwoodjs-app-api-main
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "87e663232befca16b40b48fe69d4969c103138b9"

imagePullSecrets:
  - name: redwoods

service:
  type: NodePort
  port: 8911
  targetPort: 8910

configMap:
  name: reactconfig2

ingress:
  enabled: false




