apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
  name: {{ include "api-chart.fullname" . }}
spec:
  ports:
  - name: react-port
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "api-chart.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
